.github/workflows/prover-testing.yml, .github/workflows/reuse-run-e2e-tests.yml
=> fix E2E tests node runner

prover/.golangci.yml
=> Prover: remove the G115 linting rule

settings.gradle
=> gradle: update project to Linea 

coordinator/app/src/main/kotlin/net/consensys/zkevm/coordinator/app/config/CoordinatorConfig.kt, coordinator/app/src/test/kotlin/net/consensys/zkevm/coordinator/app/config/CoordinatorConfigTest.kt, coordinator/clients/smart-contract-client/src/main/kotlin/net/consensys/linea/contract/l1/Web3JLineaRollupSmartContractClientReadOnly.kt, coordinator/core/src/main/kotlin/net/consensys/zkevm/coordinator/clients/smartcontract/LineaRollupSmartContractClient.kt, coordinator/ethereum/finalization-monitor/src/main/kotlin/net/consensys/zkevm/ethereum/finalization/FinalizationMonitorImpl.kt, coordinator/ethereum/finalization-monitor/src/test/kotlin/net/consensys/zkevm/ethereum/finalization/FinalizationMonitorImplTest.kt, coordinator/ethereum/message-anchoring/src/integrationTest/kotlin/net.consensys.zkevm.ethereum.coordination.messageanchoring/L2MessageAnchorerIntegrationTest.kt, coordinator/ethereum/message-anchoring/src/main/kotlin/net/consensys/zkevm/ethereum/coordination/messageanchoring/MessageAnchoringService.kt, jvm-libs/core/domain-models/src/main/kotlin/net/consensys/linea/BlockParameter.kt
=> coordinator: move BlockParameter to domain module

bridge-ui/src/components/layouts/MobileMenu.tsx
=> fix: bridge ui styling issue

.github/workflows/codeql.yml
=> Fixing CodeQL

docker/compose-local-dev-traces-v2.overrides.yml
=> Updating Besu version for Sequencer node

operations/Dockerfile, prover/Dockerfile
This PR implements issue(s) #3954
=> fix(3954): dockerfile deprecated features issue

.github/workflows/run-smc-tests.yml, contracts/README.md
=> feat: add golang caching in smart contracts test CI

docker/compose-local-dev-traces-v2.overrides.yml, prover/backend/execution/prove.go
This PR changes the partial prover to use the full-checker
=> feat(partial): changes the structure of the partial prover

coordinator/core/build.gradle, coordinator/ethereum/message-anchoring/src/integrationTest/kotlin/net.consensys.zkevm.ethereum.coordination.messageanchoring/L1EventQuerierIntegrationTest.kt, coordinator/ethereum/message-anchoring/src/integrationTest/kotlin/net.consensys.zkevm.ethereum.coordination.messageanchoring/L2MessageAnchorerIntegrationTest.kt, coordinator/ethereum/message-anchoring/src/integrationTest/kotlin/net.consensys.zkevm.ethereum.coordination.messageanchoring/MessageServiceIntegrationTest.kt, coordinator/ethereum/test-utils/src/main/kotlin/net/consensys/zkevm/ethereum/AccountManager.kt, coordinator/ethereum/test-utils/src/main/kotlin/net/consensys/zkevm/ethereum/ContractsManager.kt, coordinator/ethereum/test-utils/src/main/kotlin/net/consensys/zkevm/ethereum/Web3jClientManager.kt, jvm-libs/web3j-extensions/src/main/kotlin/net/consensys/linea/web3j/OkHttpClientLogging.kt
=> coordinator: add Web3jClientManager to improve test code reuse

config/coordinator/coordinator-docker-traces-v2-override.config.toml, docker/compose-local-dev-traces-v2.overrides.yml
=> Tracer update

contracts/contracts/tokenBridge/TokenBridge.sol
This PR implements issue(s) #94
=> Adding TokenBridge version for completeness

docker/compose-local-dev-traces-v2.overrides.yml
=> Trying to update Sequencer to v0.6.0-rc6.1

.github/workflows/prover-native-lib-blob-compressor-release.yml
=> Fix linux runner arch

.github/workflows/coordinator-build-and-publish.yml, .github/workflows/coordinator-testing.yml, .github/workflows/main.yml, .github/workflows/postman-build-and-publish.yml, .github/workflows/postman-testing.yml, .github/workflows/prover-build-and-publish.yml, .github/workflows/prover-testing.yml, .github/workflows/reuse-check-images-tags-and-push.yml, .github/workflows/reuse-store-image-name-and-tags.yml, .github/workflows/traces-api-facade-build-and-publish.yml, .github/workflows/traces-api-facade-testing.yml
=> Github workflow concurrency - Only cancel if branch isn't main

contracts/contracts/LineaRollup.sol, contracts/contracts/interfaces/l1/ILineaRollup.sol, contracts/deploy/03_deploy_LineaRollup.ts, contracts/test/LineaRollup.ts, contracts/test/LineaRollupInit.ts, contracts/test/utils/constants.ts, contracts/test/utils/helpers.ts
This PR implements issue(s) #3921
=> [Feat] Readd missing tests

.github/workflows/main.yml
=> Fix cleanup-deployments environment name

.github/workflows/prover-native-lib-blob-compressor-release.yml
Draft release: https://github.com/Consensys/linea-monorepo/releases/tag/untagged-3dec662428fd3a667af2
=> JNI Libs - Add linux arm64 release

jvm-libs/vertx-helper/src/main/kotlin/net/consensys/linea/vertx/ObservabilityServer.kt, jvm-libs/vertx-helper/src/test/kotlin/net/consensys/linea/vertx/ObservabilityServerTest.kt
This PR implements issue(s) #144
=> coordinator: try fix flacky ObservabilityServerTest

.github/workflows/codeql.yml
=> CodeQL - Increase runner size from small to medium

.github/workflows/all-tools.yml, .github/workflows/bridge-ui-publish.yml, .github/workflows/cache-docker-images.yml, .github/workflows/coordinator-build-and-publish.yml, .github/workflows/coordinator-testing.yml, .github/workflows/postman-build-and-publish.yml, .github/workflows/prover-build-and-publish.yml, .github/workflows/reuse-run-e2e-tests.yml, .github/workflows/reuse-tag-without-untested-suffix.yml, .github/workflows/traces-api-facade-build-and-publish.yml
* Updated buildx actions
* Updated docker login actions
* Updated docker qemu action
* Fixed docker rate limiting issues for the CI
=> Fixing dockerhub rate limiting issue on CI

.github/workflows/coordinator-build-and-publish.yml, .github/workflows/coordinator-testing.yml, .github/workflows/main.yml, .github/workflows/postman-build-and-publish.yml, .github/workflows/postman-testing.yml, .github/workflows/prover-build-and-publish.yml, .github/workflows/prover-testing.yml, .github/workflows/reuse-check-images-tags-and-push.yml, .github/workflows/reuse-store-image-name-and-tags.yml, .github/workflows/traces-api-facade-build-and-publish.yml, .github/workflows/traces-api-facade-testing.yml
=> Allow Main branch workflow concurrency

.github/workflows/postman-testing.yml, .github/workflows/prover-testing.yml, .github/workflows/reuse-run-e2e-tests.yml
=> GHA workflows - Increase runner sizes

.github/workflows/all-tools.yml, .github/workflows/bridge-ui-e2e-tests.yml, .github/workflows/bridge-ui-publish.yml, .github/workflows/cache-docker-images.yml, .github/workflows/codeql.yml, .github/workflows/coordinator-build-and-publish.yml, .github/workflows/coordinator-testing.yml, .github/workflows/finalized-tag-updater-github-release.yml, .github/workflows/load-test.yml, .github/workflows/main.yml, .github/workflows/maven-release.yml, .github/workflows/postman-build-and-publish.yml, .github/workflows/postman-testing.yml, .github/workflows/prover-build-and-publish.yml, .github/workflows/prover-native-lib-blob-compressor-release.yml, .github/workflows/prover-testing.yml, .github/workflows/reuse-check-images-tags-and-push.yml, .github/workflows/reuse-run-e2e-tests.yml, .github/workflows/reuse-store-image-name-and-tags.yml, .github/workflows/reuse-tag-without-untested-suffix.yml, .github/workflows/run-smc-tests.yml, .github/workflows/security-report-to-csv.yml, .github/workflows/stale.yml, .github/workflows/traces-api-facade-build-and-publish.yml, .github/workflows/traces-api-facade-testing.yml, .github/workflows/valid-audit-pr-has-tags.yml
=> Switch runners to ubuntu-20.04

.github/workflows/main.yml, .github/workflows/run-smc-tests.yml
=> Fix: Add pull_request trigger for CI

.github/workflows/bridge-ui-publish.yml, .github/workflows/coordinator-build-and-publish.yml, .github/workflows/reuse-run-e2e-tests.yml, .github/workflows/reuse-tag-without-untested-suffix.yml, .github/workflows/traces-api-facade-build-and-publish.yml
=> Fix: remove ci docker login condition

.github/workflows/coordinator-build-and-publish.yml, .github/workflows/main.yml, .github/workflows/postman-build-and-publish.yml, .github/workflows/prover-build-and-publish.yml, .github/workflows/reuse-run-e2e-tests.yml, .github/workflows/traces-api-facade-build-and-publish.yml
New step for manual environment deployment, build and e2e tests steps need this step to complete first
=> GHA - Single deployment for manual environment 

coordinator/ethereum/test-utils/src/main/kotlin/net/consensys/zkevm/ethereum/MakefileContractDeploymentHelper.kt, coordinator/ethereum/test-utils/src/test/kotlin/net/consensys/zkevm/ethereum/MakefileContractDeploymentHelperKtTest.kt
=> coordinator: fix integration test smart contract deploy helper

config/coordinator/coordinator-local-dev.config.overrides.toml, coordinator/app/src/test/kotlin/net/consensys/zkevm/coordinator/blockcreation/TracesFilesManagerTest.kt
=> fix coordinator local overrides file

jvm-libs/json-rpc/build.gradle, jvm-libs/json-rpc/src/main/kotlin/net/consensys/linea/jsonrpc/JsonRpcMessageProcessor.kt, jvm-libs/json-rpc/src/main/kotlin/net/consensys/linea/jsonrpc/JsonRpcRequest.kt, jvm-libs/json-rpc/src/main/kotlin/net/consensys/linea/jsonrpc/JsonRpcResponse.kt, jvm-libs/json-rpc/src/main/kotlin/net/consensys/linea/jsonrpc/client/JsonRpcClient.kt, jvm-libs/json-rpc/src/main/kotlin/net/consensys/linea/jsonrpc/client/JsonRpcRequestFanOut.kt, jvm-libs/json-rpc/src/main/kotlin/net/consensys/linea/jsonrpc/client/JsonRpcRequestRetryer.kt, jvm-libs/json-rpc/src/main/kotlin/net/consensys/linea/jsonrpc/client/JsonRpcRequestRetryerV2.kt, jvm-libs/json-rpc/src/main/kotlin/net/consensys/linea/jsonrpc/client/JsonRpcV2Client.kt, jvm-libs/json-rpc/src/main/kotlin/net/consensys/linea/jsonrpc/client/JsonRpcV2ClientImpl.kt, jvm-libs/json-rpc/src/main/kotlin/net/consensys/linea/jsonrpc/client/ObjectMappers.kt, jvm-libs/json-rpc/src/main/kotlin/net/consensys/linea/jsonrpc/client/SequentialIdSupplier.kt, jvm-libs/json-rpc/src/main/kotlin/net/consensys/linea/jsonrpc/client/VertxHttpJsonRpcClient.kt, jvm-libs/json-rpc/src/main/kotlin/net/consensys/linea/jsonrpc/client/VertxHttpJsonRpcClientFactory.kt, jvm-libs/json-rpc/src/test/kotlin/net/consensys/linea/jsonrpc/client/JsonRpcV2ClientImplTest.kt, jvm-libs/json-rpc/src/test/kotlin/net/consensys/linea/jsonrpc/client/VertxHttpJsonRpcClientTest.kt, traces-api-facade/conflation/src/main/kotlin/net/consensys/linea/traces/RawJsonTracesConflator.kt
=> JSON-RPC client improvements 

coordinator/ethereum/models-helper/build.gradle, coordinator/ethereum/models-helper/src/main/kotlin/net/consensys/zkevm/encoding/ExecutionPayloadV1RLPEncoderByBesuImplementation.kt, gradle/libs.versions.toml, jvm-libs/linea/teku-execution-client/build.gradle, jvm-libs/linea/web3j-extensions/build.gradle, jvm-libs/linea/web3j-extensions/src/main/kotlin/net/consensys/linea/web3j/DomainObjectMappers.kt
=> coordinator: update besu libs

.github/workflows/reuse-store-image-name-and-tags.yml, transaction-exclusion-api/app/build.gradle, transaction-exclusion-api/app/src/main/kotlin/net/consensys/linea/transactionexclusion/app/api/ArgumentParser.kt
=> fix: revert the change and use GITHUB_SHA for commit tag

coordinator/app/build.gradle, jvm-libs/linea/testing/teku-helper/src/main/kotlin/tech/pegasys/teku/ethereum/executionclient/schema/ExecutionPayloadV1.kt
=> Simplified executionPayloadV1 testing util

.github/ISSUE_TEMPLATE/epic.yml
=> chore(github): Add Epic/Major issue template

.github/workflows/coordinator-build-and-publish.yml, .github/workflows/postman-build-and-publish.yml, .github/workflows/prover-build-and-publish.yml, .github/workflows/traces-api-facade-build-and-publish.yml, .github/workflows/transaction-exclusion-api-build-and-publish.yml
=> fix: building temp images for e2e testing when merging back to main

.github/actions/image-tag-and-push/action.yml, .github/workflows/cache-docker-images.yml
This PR implements issue(s) #181
=> fix: correct inputs for image-tag-and-push

.github/workflows/maven-release.yml
=> Use linea subfolder for maven release

contracts/contracts/messageService/l2/L2MessageService.sol
=> [Fix] I-05 Use correct initializer value for L2MessageService

.github/workflows/coordinator-testing.yml
=> Add 15m timeout to coordinator integration tests

.github/workflows/bridge-ui-e2e-tests.yml, .github/workflows/run-smc-tests.yml
=> fix: issue with checkout job for external branches

prover/backend/blobdecompression/prove.go
This PR updates the dummy decompression proof in a way congruent with actual proofs (i.e. same public input)
=> feat decompression dummy proof

.github/workflows/main.yml, .github/workflows/testing.yml, jvm-libs/generic/persistence/db/src/testFixtures/kotlin/net/consensys/zkevm/persistence/db/test/CleanDbTestSuiteParallel.kt
This PR implements issue(s) #328
=> Fix(328): ci testing workflow issue when no tests are run

contracts/contracts/lib/CallForwardingProxy.sol, contracts/deploy/03_deploy_LineaRollupWithReinitialization.ts, contracts/deploy/04_deploy_L2MessageServiceWithReinitialization.ts, contracts/deploy/06_deploy_TokenBridgeWithReinitialization.ts, contracts/deploy/12_deploy_CallForwardingProxy.ts
=> [Chore] Update current reinitialization script for all contracts

contracts/deploy/06_deploy_TokenBridgeWithReinitialization.ts
=> [Fix] - Correct var on tokenbridge deploy

Makefile, docker/compose-local-dev-traces-v2.overrides.yml, docker/compose.yml, docker/config/blobscan/env
=> staterecover: improve local stack

contracts/contracts/test-contracts/TestLineaRollupV5.sol, contracts/test/LineaRollup.ts, contracts/test/common/helpers/expectations.ts
=> [Chore] - Validate callforwarding proxy works as expected

e2e/src/common/constants.ts, e2e/src/common/upgrades.ts, e2e/src/common/utils.ts, e2e/src/config/tests-config/environments/dev.ts, e2e/src/config/tests-config/environments/local.ts, e2e/src/config/tests-config/environments/sepolia.ts, e2e/src/config/tests-config/setup.ts, e2e/src/config/tests-config/types.ts, e2e/src/submission-finalization.spec.ts
This PR implements issue(s) #95
=> feat: add e2e tests for LineaRollup contract upgrade

contracts/README.md, docs/audits.md
=> [Chore] - Use shared audits file and link it from contracts

contracts/contracts/lib/TokenBridgePauseManager.sol, contracts/docs/api/lib/TokenBridgePauseManager.md
=> [Fix] Add NatSpec for TokenBridgePauseManager.sol

docs/audits.md
=> [Chore] - Use latest Cyfrin report

contracts/contracts/lib/TokenBridgePauseManager.sol, contracts/docs/api/lib/TokenBridgePauseManager.md
This reverts commit 77783808711ae3fd9fba808bd989ef6fe3d2d34f.
=> [Chore] Revert Natspec additions to TokenBridgePauseManager for audit purposes

.github/workflows/all-tools.yml, .github/workflows/cache-docker-images.yml, .github/workflows/coordinator-build-and-publish.yml, .github/workflows/main.yml, .github/workflows/prover-native-lib-blob-compressor-release.yml, .github/workflows/prover-testing.yml, .github/workflows/run-smc-tests.yml, .github/workflows/testing.yml, .github/workflows/traces-api-facade-build-and-publish.yml, .github/workflows/traces-api-facade-testing.yml, .github/workflows/transaction-exclusion-api-build-and-publish.yml
=> Fix: remove github actions warnings

.github/workflows/codeql.yml
=> Fix: bump code ql github action version to v3

docs/audits.md
=> [Fix] - Use latest OZ link

.github/actions/image-tag-and-push/action.yml, .github/workflows/bridge-ui-e2e-tests.yml, .github/workflows/codeql.yml, .github/workflows/coordinator-testing.yml, .github/workflows/prover-native-lib-blob-compressor-release.yml, .github/workflows/run-smc-tests.yml, .github/workflows/security-report-to-csv.yml, .github/workflows/valid-audit-pr-has-tags.yml
=> fix: update github actions versions

contracts/deploy/06_deploy_TokenBridge.ts
=> [Fix] - Use correct var name

docker/compose.yml
=> Feat: update postman docker image version in local stack

prover/backend/execution/prove.go
=> fix(prod): removes check failing on prod.

docs/architecture-description.md
Updated the Prover API specs in the Linea architecture docs.
=> feature:440 - update prover api specs

.github/workflows/prover-native-lib-blob-compressor-release.yml
Fixes CHA runners to make release of compressor binary libs
=> Fix prover libs CI release 

contracts/.solhint.json, contracts/.solhintignore, contracts/contracts/lib/CallForwardingProxy.sol, contracts/contracts/test-contracts/RevertingVerifier.sol, contracts/package.json, contracts/test/LineaRollup.ts, pnpm-lock.yaml
=> [Chore] bump hardhat and reduce lint warnings

docker/compose-local-dev-traces-v2.overrides.yml, docker/compose.yml
=> Besu update

e2e/src/bridge-tokens.spec.ts, e2e/src/common/deployments.ts, e2e/src/common/utils.ts, e2e/src/gas-limit.spec.ts, e2e/src/l2.spec.ts, e2e/src/messaging.spec.ts, e2e/src/restart.spec.ts, e2e/src/submission-finalization.spec.ts, e2e/src/transaction-exclusion.spec.ts
=> Fix: clean e2e tests logs

.github/workflows/finalized-tag-updater-github-release.yml, .github/workflows/main.yml
=> [Fix] Remove dead code for finalized-tag-updater-github-release.yml automatic trigger

contracts/contracts/interfaces/l1/ILineaRollup.sol, contracts/contracts/test-contracts/LineaRollupV5.sol, contracts/docs/api/interfaces/l1/ILineaRollup.mdx
=> [Fix] stucture typo

contracts/docs/api/tokenBridge/lib/StorageFiller39.mdx, contracts/hardhat.config.ts
=> [Fix] remove empty *.mdx page for storagefiller39

docker/compose.yml
=> Updating sequencer

docs/audits.md
=> [Chore] - Update Cyfrin audit link

prover/protocol/distributed/compiler/inclusion/inclusion_test.go, prover/protocol/wizard/prover.go
=> alex: some ideas

prover/Dockerfile
=> prover: Dockerfile remove legacy/unused data/work folder

.github/workflows/all-tools.yml, .github/workflows/postman-build-and-publish.yml, .github/workflows/prover-build-and-publish.yml
This PR implements issue(s) #541
=> [Fix] remove SELF_GITHUB_SSH_KEY

.github/workflows/reuse-github-release-besu-plugin.yml, .github/workflows/staterecovery-testing.yml, state-recovery/besu-plugin/jreleaser.yml
=> staterecovery: add github release

jvm-libs/generic/json-rpc/src/test/kotlin/net/consensys/linea/jsonrpc/client/VertxHttpJsonRpcClientTest.kt
=> jvm-libs/jsonrpc fix flacky test

.github/workflows/reuse-github-release-besu-plugin.yml, docker/compose.yml, state-recovery/besu-plugin/build.gradle, state-recovery/besu-plugin/jreleaser.yml
=> staterecovery: github release fix

docker/compose.yml, docker/config/l1-node/cl/network-config.yml, docker/config/l1-node/el/config.toml
=> Local stack update

.github/workflows/all-tools.yml, .github/workflows/bridge-ui-e2e-tests.yml, .github/workflows/cache-docker-images.yml, .github/workflows/codeql.yml, .github/workflows/load-test.yml, .github/workflows/main.yml, .github/workflows/postman-testing.yml, .github/workflows/reuse-check-images-tags-and-push.yml, .github/workflows/reuse-store-image-name-and-tags.yml, .github/workflows/run-smc-tests.yml, .github/workflows/security-report-to-csv.yml, .github/workflows/stale.yml, .github/workflows/valid-audit-pr-has-tags.yml
This PR implements issue(s) #582
=> [Feat] Github Workflows - Substitute old for new runner

coordinator/core/src/main/kotlin/net/consensys/zkevm/ethereum/coordination/aggregation/GlobalAggregationCalculator.kt, coordinator/core/src/main/kotlin/net/consensys/zkevm/ethereum/coordination/aggregation/ProofAggregationCoordinatorService.kt, coordinator/core/src/main/kotlin/net/consensys/zkevm/ethereum/coordination/blob/BlobCompressionProofCoordinator.kt, coordinator/core/src/main/kotlin/net/consensys/zkevm/ethereum/coordination/conflation/ConflationServiceImpl.kt, coordinator/core/src/test/kotlin/net/consensys/zkevm/ethereum/coordination/aggregation/ProofAggregationCoordinatorServiceTest.kt
This PR implements issue(s) #[3128](https://github.com/Consensys/zkevm-monorepo/issues/3128)
=> 3128 export metrics for conflation blob and aggregation size

docker/compose.yml, docker/config/l1-node/cl/config.yaml, docker/config/l1-node/cl/log4j.xml, docker/config/l1-node/el/config.toml, docker/config/l1-node/el/log4j.xml
=> L1 client config improv

jvm-libs/generic/extensions/futures/src/test/kotlin/net/consensys/linea/async/AsyncRetryerTest.kt
This PR implements issue(s) #257
=> AsyncRetryerTest: fix flacky test

e2e/src/transaction-exclusion.spec.ts, jvm-libs/linea/testing/l1-blob-and-proof-submission/src/main/kotlin/net/consensys/linea/testing/submission/SubmissionTestHelper.kt
=> small fix on tests

postman/Dockerfile
=> fix: temp fix for the corepack issue

jvm-libs/generic/json-rpc/src/test/kotlin/net/consensys/linea/jsonrpc/client/JsonRpcV2ClientImplTest.kt
This PR implements issue(s) #252
=> jvm-libs: fix flacky unit test on JSON-RPC

.github/workflows/reuse-run-e2e-tests.yml
=> Fixing logs collection in case of E2E tests failure on CI

docs/get-started.md
This PR improves the "Get Started" documentation and fixes the main command to run the stack.
=> doc: Improve the "Get Started" section

prover/protocol/distributed/compiler/permutation/permutation_test.go, prover/protocol/distributed/compiler/permutation/settings.go, prover/protocol/distributed/distributed.go, prover/protocol/distributed/lpp/lpp.go, prover/protocol/distributed/namebaseddiscoverer/period_separating_module_discoverer.go, prover/protocol/distributed/namebaseddiscoverer/query_based_module_discoverer.go, prover/utils/collection/mapping.go
=> added more functionalities to the discoverer

contracts/src/_testing/mocks/tokens/TestERC20.sol, contracts/src/bridging/token/BridgedToken.sol, contracts/src/bridging/token/CustomBridgedToken.sol, contracts/src/bridging/token/TokenBridge.sol, contracts/src/bridging/token/interfaces/ITokenBridge.sol, contracts/src/tokens/LineaSurgeXP.sol, contracts/src/tokens/LineaVoyageXP.sol
This PR implements issue(s) #611
=> smart contract doc changes for erc-20

config/coordinator/coordinator-docker-traces-v2-override.config.toml, docker/compose-spec-l2-services.yml, docker/compose-tracing-v2.yml
=> Updating tracer plugin and traces API

bridge-ui/src/components/bridge/BridgeLayout.tsx
This PR implements issue(s) #697
=> feat: add warning message for usdc bridging

.github/workflows/bridge-ui-e2e-tests.yml, .github/workflows/bridge-ui-publish.yml
=> Fix: skip bridge UI e2e test and docker build for forked PR

.github/workflows/bridge-ui-e2e-tests.yml, .github/workflows/bridge-ui-publish.yml
- Update bridge ui e2e tests workflow paths filters
- Remove unecessary action in bridge UI build workflow
=> Fix: update bridge ui e2e tests paths filters

jvm-libs/linea/blob-decompressor/build.gradle, jvm-libs/linea/blob-decompressor/src/main/kotlin/net/consensys/linea/blob/GoNativeBlobDecompressor.kt, jvm-libs/linea/blob-decompressor/src/test/kotlin/net/consensys/linea/blob/BlobDecompressorDataDecodingTest.kt, jvm-libs/linea/blob-decompressor/src/test/kotlin/net/consensys/linea/blob/GoNativeBlobDecompressorTest.kt, state-recovery/appcore/logic/build.gradle, state-recovery/test-cases/build.gradle, state-recovery/test-cases/src/e2eTest/kotlin/linea/staterecovery/StateRecoveryE2ETest.kt, transaction-decoder-tool/src/test/kotlin/linea/test/BlockEncodingValidator.kt
=> sataterecovery: use decompressor that is ThreadSafe

contracts/src/bridging/token/TokenBridge.sol, contracts/src/bridging/token/interfaces/ITokenBridge.sol
This PR implements issue(s) #707
=> [Fix] Tokenbridge.sol comment typos

contracts/docs/api/bridging/token/TokenBridge.mdx, contracts/docs/api/bridging/token/interfaces/ITokenBridge.mdx, contracts/foundry.toml, contracts/test/foundry/LineaRollup.t.sol
This PR implements issue(s) #691
=> [Fix] Foundry version to 1.0

.gitmodules, prover/Makefile
- remove rust corset submodule
- add go-corset submodule
- use go-corset in Makefile
=> feat(go-corset): go-corset as submodule

docs/architecture-description.md
=> [Fix] Update architecture doc; run architecture doc through spell-checker/grammar AI

bridge-ui/next.config.mjs, bridge-ui/src/components/bridge/BridgeLayout.tsx
=> Fix: update bridge ui USDC warning message

prover/protocol/compiler/mimc/mimc.go
=> apply `manualCheckMiMCBlock` individually to each query’s columns

buildSrc/src/main/groovy/net.consensys.zkevm.kotlin-common-minimal-conventions.gradle, config/coordinator/coordinator-docker-traces-v2-override.config.toml, docker/compose-spec-l1-services.yml, docker/compose-spec-l2-services.yml, finalized-tag-updater/build.gradle, jvm-libs/linea/besu-libs/build.gradle
This PR implements issue(s) #[4184](https://github.com/Consensys/zkevm-monorepo/issues/4184)
=> feat: update build.gradle to org.hyperledger and linea-besu-upstream

bridge-ui/src/components/bridge/bridge-layout/index.tsx, bridge-ui/src/components/bridge/claiming/fees/with-fees/index.tsx, bridge-ui/src/hooks/fees/useFees.ts, bridge-ui/src/hooks/fees/useGasFees.ts, bridge-ui/src/hooks/fees/useMinimumFee.ts, bridge-ui/src/stores/formStore.ts, bridge-ui/src/types/index.ts, bridge-ui/src/types/providers.ts
=> fix: fees calculation issue

bridge-ui/src/hooks/useMinimumFee.ts
=> fix: update minimumFeeInWei function abi

bridge-ui/RELEASE-NOTES.md, bridge-ui/package.json
=> fix: update bridge ui version

config/coordinator/coordinator-docker-traces-v2-override.config.toml, docker/compose-spec-l1-services.yml, docker/compose-spec-l2-services.yml, docker/compose-tracing-v1-ci-extension.yml, docker/compose-tracing-v1.yml, docker/compose-tracing-v2.yml, docker/config/l2-node-besu/l2-node-besu-config.toml, docker/config/linea-besu-sequencer/sequencer.config.toml, docker/config/traces-node-v2/traces-node-v2-config.toml, docker/linea-sepolia/linea-besu.config.toml
This PR is to update the local stack with linea-besu-package for [Besu 25.3](https://github.com/hyperledger/besu/releases/tag/25.3.0)
=> feat: updated linea-besu-package in local stack

prover/zkevm/prover/statemanager/statesummary/arithmetization_connector.go
=> minor(bv2): comments out the failing lookups

bridge-ui/RELEASE-NOTES.md, bridge-ui/package.json
=> Fix: update release notes and package json version

bridge-ui/src/app/native-bridge/page.tsx
=> fix: remove usdc warning message in the bridge ui

bridge-ui/src/components/bridge/amount/index.tsx, bridge-ui/src/components/bridge/claiming/index.tsx, bridge-ui/src/components/bridge/claiming/received-amount/index.tsx, bridge-ui/src/components/bridge/claiming/skeleton/index.tsx, bridge-ui/src/components/bridge/claiming/skeleton/skeleton.module.scss, bridge-ui/src/components/bridge/from-chain/index.tsx, bridge-ui/src/components/bridge/modal/token-modal/index.tsx, bridge-ui/src/components/bridge/modal/token-modal/token-details/index.tsx, bridge-ui/src/components/bridge/swap-chain/swap-chain.module.scss, bridge-ui/src/components/bridge/to-chain/index.tsx, bridge-ui/src/components/bridge/token-list/index.tsx, bridge-ui/src/constants/general.ts, bridge-ui/src/constants/index.ts, bridge-ui/src/constants/tokens.ts, bridge-ui/src/hooks/fees/useBridgingFee.ts, bridge-ui/src/hooks/fees/useEthBridgingFee.ts, bridge-ui/src/hooks/fees/useFees.ts, bridge-ui/src/hooks/fees/useGasFees.ts, bridge-ui/src/hooks/transaction-args/cctp/useDepositForBurnTxArgs.ts, bridge-ui/src/hooks/transaction-args/useApproveTxArgs.ts, bridge-ui/src/hooks/transaction-args/useClaimTransactionTxArgs.ts, bridge-ui/src/hooks/transaction-args/useERC20BridgeTxArgs.ts, bridge-ui/src/hooks/transaction-args/useEthBridgeTxArgs.ts, bridge-ui/src/hooks/transaction-args/useTransactionArgs.ts, bridge-ui/src/utils/index.ts, bridge-ui/src/utils/utils.ts
=> Fix: display fees for non connected users

bridge-ui/package.json, bridge-ui/src/components/bridge/claiming/received-amount/index.tsx, bridge-ui/src/components/bridge/swap-chain/index.tsx, bridge-ui/src/services/tokenService.ts, bridge-ui/src/utils/tokens.ts, pnpm-lock.yaml
- remove native tokens that don't have L1 address in the token list
- fix receive amount value in the native bridge
- bump next js version to patch this https://nextjs.org/blog/cve-2025-29927
=> Fix: remove native tokens, fix receive amount value and bump next js version

bridge-ui/package.json, bridge-ui/src/app/native-bridge/layout.tsx, bridge-ui/src/app/native-bridge/page.module.scss, bridge-ui/src/app/native-bridge/page.tsx, bridge-ui/src/app/page.module.scss, bridge-ui/src/app/page.tsx, bridge-ui/src/components/bridge/bridge-layout/index.tsx, bridge-ui/src/components/bridge/destination-address/index.tsx, bridge-ui/src/components/bridge/form/index.tsx, bridge-ui/src/components/bridge/submit/index.tsx, bridge-ui/src/components/bridge/submit/submit.module.scss, bridge-ui/src/components/layouts/Layout.tsx, bridge-ui/src/components/layouts/layout.module.scss, bridge-ui/src/hooks/useTransactionHistory.ts, pnpm-lock.yaml
=> Fix: wallet button for non connected user and bridge layout issue

.github/workflows/bridge-ui-e2e-tests.yml, bridge-ui/src/components/bridge/submit/index.tsx, bridge-ui/test/advancedFixtures.ts, bridge-ui/test/e2e/bridge-l1-l2.spec.ts
This PR implements issue(s) #821
=> [Fix] Bridge UI switch network prompt

config/coordinator/coordinator-docker.config.toml, config/coordinator/coordinator-local-dev.config-traces-v2.overrides.toml, config/coordinator/coordinator-local-dev.config.overrides.toml, coordinator/app/src/main/kotlin/net/consensys/zkevm/coordinator/app/L1DependentApp.kt, coordinator/app/src/main/kotlin/net/consensys/zkevm/coordinator/app/config/CoordinatorConfig.kt, coordinator/app/src/test/kotlin/net/consensys/zkevm/coordinator/app/config/CoordinatorConfigTest.kt, coordinator/app/src/test/resources/configs/coordinator.config.toml, docker/compose-spec-l2-services.yml
=> coordinator: update Shomei frontend at LATEST finalization

config/coordinator/coordinator-docker-traces-v2-override.config.toml, docker/compose-spec-l1-services.yml, docker/compose-spec-l2-services.yml, state-recovery/besu-plugin/src/main/kotlin/linea/staterecovery/plugin/LineaStateRecoveryPlugin.kt, state-recovery/besu-plugin/src/main/kotlin/linea/staterecovery/plugin/PluginOptions.kt, state-recovery/test-cases/src/integrationTest/kotlin/linea/staterecovery/StateRecoveryWithRealBesuAndStateManagerIntTest.kt, state-recovery/test-cases/src/main/kotlin/linea/staterecovery/test/FakeStateManagerClient.kt, state-recovery/test-cases/src/test/kotlin/linea/staterecovery/test/AssertionsHelper.kt
=> staterecovery: fix 2B block gas limit

.github/workflows/codecov-external-pr.yml
=> [Fix] Codecov external PR CI trigger

bridge-ui/src/components/bridge/transaction-history/list-transaction/item/index.tsx, bridge-ui/src/components/lifi/widget/index.tsx
=> Fix: remove lifi chains default values and fix estimated time in history

config/coordinator/coordinator-docker.config.toml, coordinator/app/src/main/kotlin/net/consensys/zkevm/coordinator/app/config/CoordinatorConfig.kt, coordinator/app/src/test/kotlin/net/consensys/zkevm/coordinator/app/config/CoordinatorConfigTest.kt, coordinator/app/src/test/resources/configs/coordinator.config.toml
=> coordinator: fix feature toggle

bridge-ui/src/components/lifi/widget/index.tsx, bridge-ui/src/constants/tokens.ts, bridge-ui/src/services/tokenService.ts
=> Fix: update token list order + add Linea as default lifi destination chain

contracts/README.md
Add a small tweak for the verifier
=> [Chore ] Small documentation tweak

contracts/package.json, pnpm-lock.yaml
This bumps hardhat to support Prague
=> [Chore] Bumping hardhat

postman/scripts/helpers.ts, postman/scripts/manualTestSendMessages.ts, postman/scripts/sendMessageOnL1.ts
This PR implements issue(s) #793
=> [Feat] Postman Sponsorship manual test script

.github/workflows/bridge-ui-publish.yml
=> [Fix] Bridge-UI Docker build in CI

coordinator/ethereum/message-anchoring-i2/src/main/kotlin/linea/anchoring/clients/L1MessageSentEventsFetcher.kt, coordinator/ethereum/message-anchoring-i2/src/main/kotlin/linea/anchoring/events/MessageSentEvent.kt, coordinator/ethereum/message-anchoring-i2/src/test/kotlin/linea/anchoring/MessageAnchoringAppTest.kt, coordinator/ethereum/message-anchoring-i2/src/test/kotlin/linea/anchoring/ModelsFactory.kt, coordinator/ethereum/message-anchoring-i2/src/test/kotlin/linea/anchoring/events/MessageSentEventTest.kt, jvm-libs/linea/clients/eth-logs-searcher/src/test/kotlin/linea/ethapi/LogsSearcherIntTest.kt, jvm-libs/linea/web3j-extensions/src/main/kotlin/linea/web3j/Blob.kt, jvm-libs/linea/web3j-extensions/src/main/kotlin/linea/web3j/RequestHelper.kt, jvm-libs/linea/web3j-extensions/src/main/kotlin/linea/web3j/ethapi/Web3jEthApiClient.kt, jvm-libs/linea/web3j-extensions/src/main/kotlin/linea/web3j/transactionmanager/AsyncFriendlyTransactionManager.kt
=> coordinator: improve web3j request error handling and fix message anchoring Event serialization

bridge-ui/test/e2e/bridge-l1-l2.spec.ts
=> [Fix] Bridge-UI e2e test fix

bridge-ui/src/components/lifi/widget/index.tsx
=> Feat: add symbiosis as bridge provider to the lifi widget

coordinator/ethereum/message-anchoring-i2/src/main/kotlin/linea/anchoring/MessageAnchoringApp.kt, coordinator/ethereum/message-anchoring-i2/src/main/kotlin/linea/anchoring/clients/L1MessageSentEventsPoller.kt, coordinator/ethereum/message-anchoring-i2/src/test/kotlin/linea/anchoring/MessageAnchoringAppTest.kt, coordinator/ethereum/message-anchoring-i2/src/test/kotlin/linea/anchoring/fakes/FakeL2MessageService.kt
=> coordinator: message anchoring - fix test after queue refactor

prover/circuits/pi-interconnection/circuit.go, prover/cmd/dev-tools/corset-checker/main.go, prover/crypto/vortex/commitment.go, prover/crypto/vortex/commitment_test.go, prover/crypto/vortex/gnark_test.go, prover/crypto/vortex/gnark_utils.go, prover/crypto/vortex/opening_prover.go, prover/crypto/vortex/opening_verifier.go, prover/crypto/vortex/params.go, prover/crypto/vortex/reedsolomon_test.go, prover/example/test_cases/framework_test.go, prover/protocol/compiler/recursion/actions.go, prover/protocol/compiler/recursion/recursion.go, prover/protocol/compiler/selfrecursion/column_opening.go, prover/protocol/compiler/selfrecursion/context.go, prover/protocol/compiler/selfrecursion/lincomb_phase.go, prover/protocol/compiler/selfrecursion/precomputations.go, prover/protocol/compiler/selfrecursion/roothashandq.go, prover/protocol/compiler/vortex/compiler.go, prover/protocol/compiler/vortex/gnark_verifier.go, prover/protocol/compiler/vortex/gnark_verifier_test.go, prover/protocol/compiler/vortex/option.go, prover/protocol/compiler/vortex/prover.go, prover/protocol/compiler/vortex/verifier.go, prover/protocol/compiler/vortex/vortex_test.go, prover/zkevm/full.go, prover/zkevm/partial.go
=> Prover/Adding the Optional SIS Hashing Feature in the Vortex Protocol

.github/workflows/bridge-ui-publish.yml, bridge-ui/src/app/faq/page.tsx, bridge-ui/src/utils/message.ts
=> fix: update l2 to L1 bridge estimated time

coordinator/ethereum/message-anchoring-i2/src/main/kotlin/linea/anchoring/MessageAnchoringApp.kt, coordinator/ethereum/message-anchoring-i2/src/main/kotlin/linea/anchoring/MessageAnchoringService.kt, coordinator/ethereum/message-anchoring-i2/src/main/kotlin/linea/anchoring/clients/L1MessageSentEventsFetcher.kt, coordinator/ethereum/message-anchoring-i2/src/main/kotlin/linea/anchoring/clients/L1MessageSentEventsPoller.kt, coordinator/ethereum/message-anchoring-i2/src/test/kotlin/linea/anchoring/MessageAnchoringAppTest.kt, coordinator/ethereum/message-anchoring-i2/src/test/kotlin/linea/anchoring/fakes/FakeL2MessageService.kt, jvm-libs/linea/clients/eth-logs-searcher/src/main/kotlin/linea/ethapi/EthLogsSearcherImpl.kt
=> Tried improving the queue usage for the anchoring

.github/workflows/codecov-external-pr.yml, .github/workflows/reuse-store-image-name-and-tags.yml, .github/workflows/run-smc-tests.yml, .github/workflows/testing.yml
This PR implements issue(s) #847
=> [Fix] Codecov report for external contributor CI

prover/protocol/dedicated/plonk/alignment.go
Fixed race condition in the prepareWitnesses function: before the fix, goroutine used to change numEffWitnesses, but the top-level method did not wait for the goroutine to complete, which caused the usage of the numEffWitnesses before it changed in the other methods.
The race condition behaviour can be checked by running the following command in the `./prover` package
```
go test -race -count=1 ./zkevm/prover/ecpair
```
This PR implements issue(s) #todo
Special thanks to @OmegaTymbJIep
=> Fixed race condition in the prepareWitnesses function

bridge-ui/src/utils/message.ts
=> fix: update estimated time for L2 to L1 usdc bridging

.github/workflows/bridge-ui-publish.yml
=> Fix: increase js memory allocation for bridge ui build

postman/scripts/manualTestSendMessages.ts
=> [Fix] Postman test script to fire tx in serial

besu-plugins/state-recovery/besu-plugin/src/main/kotlin/linea/staterecovery/plugin/AppConfigurator.kt, besu-plugins/state-recovery/besu-plugin/src/main/kotlin/linea/staterecovery/plugin/LineaStateRecoveryPlugin.kt, besu-plugins/state-recovery/besu-plugin/src/main/kotlin/linea/staterecovery/plugin/PluginOptions.kt, besu-plugins/state-recovery/clients/blobscan-client/build.gradle, besu-plugins/state-recovery/clients/blobscan-client/src/main/kotlin/linea/http/vertx/StaticVertxHttpRequestRateLimiter.kt, besu-plugins/state-recovery/clients/blobscan-client/src/main/kotlin/linea/http/vertx/VertxHttpLoggingFormatter.kt, besu-plugins/state-recovery/clients/blobscan-client/src/main/kotlin/linea/http/vertx/VertxHttpRequestSender.kt, besu-plugins/state-recovery/clients/blobscan-client/src/main/kotlin/linea/http/vertx/VertxHttpRequestSenderFactory.kt, besu-plugins/state-recovery/clients/blobscan-client/src/main/kotlin/linea/http/vertx/VertxRequestLogger.kt, besu-plugins/state-recovery/clients/blobscan-client/src/main/kotlin/linea/http/vertx/VertxRequestRetrier.kt, besu-plugins/state-recovery/clients/blobscan-client/src/main/kotlin/linea/staterecovery/clients/blobscan/BlobScanClient.kt, besu-plugins/state-recovery/clients/blobscan-client/src/main/kotlin/linea/staterecovery/clients/blobscan/VertxRestClient.kt, besu-plugins/state-recovery/clients/blobscan-client/src/test/kotlin/linea/http/vertx/FakeRequestSender.kt, besu-plugins/state-recovery/clients/blobscan-client/src/test/kotlin/linea/http/vertx/StaticVertxHttpRequestRateLimiterTest.kt, besu-plugins/state-recovery/clients/blobscan-client/src/test/kotlin/linea/http/vertx/VertxHttpRequestRateLimiterAndRetryTest.kt, besu-plugins/state-recovery/clients/blobscan-client/src/test/kotlin/linea/http/vertx/VertxRestLoggingFormatterTest.kt, besu-plugins/state-recovery/clients/blobscan-client/src/test/kotlin/linea/http/vertx/VertxRestRequestLoggerTest.kt, besu-plugins/state-recovery/clients/blobscan-client/src/test/kotlin/linea/staterecovery/clients/blobscan/BlobScanClientTest.kt, besu-plugins/state-recovery/test-cases/src/test/kotlin/linea/staterecovery/ManualTestWithFakeExecutionClient.kt, jvm-libs/generic/extensions/futures/src/main/kotlin/net/consensys/linea/async/AsyncRetryer.kt
=> Staterecovery - blobscan request ratelimit 

besu-plugins/state-recovery/clients/blobscan-client/src/main/kotlin/linea/http/vertx/StaticVertxHttpRequestRateLimiter.kt, besu-plugins/state-recovery/clients/blobscan-client/src/test/kotlin/linea/http/vertx/VertxHttpRequestRateLimiterAndRetryTest.kt
=> staterecovery: fix ratelimit bug

.github/workflows/linea-besu-package-release.yml
This PR implements issue(s) #877 and #878
=> feat: add path filtering on pull requests

.github/workflows/linea-besu-package-release.yml, .github/workflows/reuse-linea-besu-package-build-test-push.yml
=> feat: enforced image only pushed to dockerhub for manual release

.github/workflows/linea-besu-package-release.yml
This PR implements issue(s) #877 and #878
=> feat: always pushed image for manual workflow

besu-plugins/state-recovery/clients/blobscan-client/build.gradle, docker/compose-spec-l2-services.yml, gradle/libs.versions.toml
=> coordinator: update image in local stack

docker/compose-spec-l2-services.yml
=> localstack: update prover and coordinator

bridge-ui/package.json, pnpm-lock.yaml
=> Fix: bump layerswap widget version in bridge ui

bridge-ui/README.md, bridge-ui/RELEASE-NOTES.md, docs/architecture-description.md, e2e/README.md, gradle/publishing.gradle
This PR implements issue(s) #614
=> [Chore] Remove inaccessible and old zkevm-monorepo refs

coordinator/app/src/main/kotlin/net/consensys/zkevm/coordinator/app/L1DependentApp.kt, coordinator/ethereum/blob-submitter/src/main/kotlin/net/consensys/zkevm/ethereum/submission/BlobSubmissionCoordinator.kt
=> coordinator: fix blob submission config

coordinator/app/src/main/kotlin/net/consensys/zkevm/coordinator/app/L1DependentApp.kt, coordinator/ethereum/message-anchoring/src/main/kotlin/linea/anchoring/MessageAnchoringApp.kt, coordinator/ethereum/message-anchoring/src/main/kotlin/linea/anchoring/clients/L1MessageSentEventsFetcher.kt, coordinator/ethereum/message-anchoring/src/main/kotlin/linea/anchoring/clients/L1MessageSentEventsPoller.kt, coordinator/ethereum/message-anchoring/src/test/kotlin/linea/anchoring/MessageAnchoringAppTest.kt
=> coordinator: fix message anchoring config

besu-plugins/state-recovery/appcore/logic/src/test/kotlin/linea/staterecovery/BlobDecompressorAndDeserializerV1Test.kt, config/coordinator/coordinator-docker.config.toml, coordinator/app/src/test/kotlin/net/consensys/zkevm/coordinator/app/config/CoordinatorConfigTest.kt, coordinator/app/src/test/resources/configs/coordinator.config.toml, coordinator/core/src/main/kotlin/net/consensys/zkevm/ethereum/coordination/blob/BlobCompressor.kt, coordinator/core/src/test/kotlin/net/consensys/zkevm/coordination/blob/GoBackedBlobCompressorTest.kt, coordinator/core/src/testFixtures/kotlin/net/consensys/zkevm/domain/BlobRecord.kt, jvm-libs/linea/blob-compressor/build.gradle, jvm-libs/linea/blob-compressor/src/main/kotlin/linea/blob/BlobCompressor.kt, jvm-libs/linea/blob-compressor/src/main/kotlin/net/consensys/linea/blob/GoNativeBlobCompressor.kt, jvm-libs/linea/blob-compressor/src/test/java/linea/blob/CompressorJavaAccessTest.java, jvm-libs/linea/blob-compressor/src/test/kotlin/linea/blob/GoBackedBlobCompressorTest.kt, jvm-libs/linea/blob-compressor/src/test/kotlin/net/consensys/linea/blob/GoNativeCompressorAndShnarfCalculatorIntTest.kt, jvm-libs/linea/blob-decompressor/src/test/kotlin/net/consensys/linea/blob/GoNativeBlobDecompressorTest.kt, jvm-libs/linea/blob-shnarf-calculator/build.gradle, jvm-libs/linea/blob-shnarf-calculator/src/main/kotlin/net/consensys/linea/blob/GoNativeBlobShnarfCalculator.kt, jvm-libs/linea/blob-shnarf-calculator/src/test/kotlin/net/consensys/linea/blob/GoNativeBlobShnarfCalculatorTest.kt, transaction-decoder-tool/src/test/kotlin/linea/test/BlockEncodingValidator.kt
This PR implements issue(s) #1008
=> coordinator: add compressedSize(data) to compressor

.github/actions/linea-besu-package/assemble/action.yml, .github/workflows/codecov-external-pr.yml, .github/workflows/reuse-store-image-name-and-tags.yml, prover/Makefile
This PR implements issue(s) #847
=> [Fix] Explicitly set commit tags from git commits to 7 characters for deterministic CI

contracts/hardhat.config.ts, contracts/test/hardhat/rollup/LineaRollup/BlobSubmission.ts
=> Fix: set hardfork to prague for hardhar test

prover/protocol/compiler/globalcs/quotient.go
=> fix(log): remove extranous units

contracts/src/bridging/token/interfaces/ITokenBridge.sol, contracts/src/interfaces/IGenericErrors.sol, contracts/src/messaging/l2/L2MessageService.sol, contracts/src/rollup/LineaRollup.sol
Removes unused errors and fixes shadowed variable
=> [Chore] Tweak contracts post Aderyn run

docker/compose-spec-l2-services.yml
=> fix: update postman docker image tag in the local stack

.github/workflows/linea-sequencer-plugin-testing.yml, besu-plugins/linea-sequencer/sequencer/build.gradle
This PR implements issue(s) #1099
=> [WIP Fix] Linea Sequencer Plugin Unit Tests

gradle/libs.versions.toml
=> Update Tracer to beta-v3.1-rc2

bridge-ui/package.json, operations/package.json, pnpm-lock.yaml
Following Dependabot's PR #1094
=> chore(dependencies): update outdated dependencies

bridge-ui/src/middleware.ts
=> fix(bridge-ui): local CSP header for development

bridge-ui/src/app/RootLayout.tsx, bridge-ui/src/middleware.ts
This PR implements issue(s) #964
=> chore(bridge-ui): add a CSP header

gradle/libs.versions.toml
=> Chore: update arithmetization to beta-v3.1-rc3

.github/workflows/slack-notify-external-contributions.yml
=> fix(ops): on external Issue creation, notify Slack

.github/workflows/slack-notify-external-contributions.yml
=> fix(ci): input sanitizing on Slack pipeline

.github/workflows/codeql.yml, .github/workflows/main.yml
=> chore(ci): improve CodeQL analysis

.github/workflows/maven-release-all.yml, jvm-libs/linea/clients/linea-contract-clients/src/testFixtures/kotlin/linea/contract/l1/FakeLineaRollupSmartContractClient.kt
This is necessary for tests in Maru, but it can be useful for coordinator or besu plugins tests.
=> coordinator: adds FakeLineaRollupSmartContractClient

bridge-ui/src/middleware.ts
This PR implements issue(s) #964
=> [BridgeUI Fix] Add intercom path to csp whitelist

bridge-ui/src/middleware.ts
=> fix: update csp headers in bridge ui

.github/workflows/reuse-linea-besu-package-run-e2e-tests.yml
=> Fix: correct the name of the traces-node container when collecting Docker logs

prover/protocol/column/verifiercol/concat_tiny_cols_test.go, prover/protocol/compiler/selfrecursion/selfrecursion_test.go, prover/protocol/compiler/vortex/prover.go, prover/protocol/compiler/vortex/verifier.go, prover/protocol/compiler/vortex/vortex_test.go, prover/protocol/dedicated/functionals/eval_coeff_test.go
=> Prover: adds more tests to debug the vortex compiler

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/operational_task_template.md, .github/workflows/main.yml
This adds an additional line to the issue templates so that creators can decide if the audience is appropriate.
=> [Chore] Add consideration to templates

config/coordinator/coordinator-config-v2.toml, coordinator/app/src/main/kotlin/linea/coordinator/config/v2/L2NetworkGasPricingConfig.kt, coordinator/app/src/main/kotlin/linea/coordinator/config/v2/toml/CoordinatorConfigFilesToml.kt, coordinator/app/src/main/kotlin/linea/coordinator/config/v2/toml/L2NetworkGasPricingConfigToml.kt, coordinator/app/src/main/kotlin/net/consensys/zkevm/coordinator/app/L1DependentApp.kt, coordinator/app/src/main/kotlin/net/consensys/zkevm/coordinator/app/L2NetworkGasPricingService.kt, coordinator/app/src/main/kotlin/net/consensys/zkevm/coordinator/blockcreation/BlockCreationMonitor.kt, coordinator/app/src/test/kotlin/linea/coordinator/config/v2/L2NetWorkingGasPricingConfigParsingTest.kt, coordinator/ethereum/gas-pricing/src/main/kotlin/net/consensys/linea/ethereum/gaspricing/DynamicGasPrice.kt, coordinator/ethereum/gas-pricing/static-cap/src/main/kotlin/net/consensys/linea/ethereum/gaspricing/staticcap/ExtraDataV1PricerService.kt, coordinator/ethereum/gas-pricing/static-cap/src/main/kotlin/net/consensys/linea/ethereum/gaspricing/staticcap/L2CalldataBasedVariableFeesCalculator.kt, coordinator/ethereum/gas-pricing/static-cap/src/main/kotlin/net/consensys/linea/ethereum/gaspricing/staticcap/L2CalldataSizeAccumulatorImpl.kt, coordinator/ethereum/gas-pricing/static-cap/src/test/kotlin/net/consensys/linea/ethereum/gaspricing/staticcap/ExtraDataV1PricerServiceTest.kt, coordinator/ethereum/gas-pricing/static-cap/src/test/kotlin/net/consensys/linea/ethereum/gaspricing/staticcap/L2CalldataBasedVariableFeesCalculatorTest.kt, coordinator/ethereum/gas-pricing/static-cap/src/test/kotlin/net/consensys/linea/ethereum/gaspricing/staticcap/L2CalldataSizeAccumulatorImplTest.kt, jvm-libs/linea/web3j-extensions/src/main/kotlin/linea/web3j/ExtendedWeb3J.kt
This PR implements issue(s) https://github.com/Consensys/zkevm-monorepo/issues/4249
=> feat: add calldata based pricing for variable cost

e2e/src/common/utils.ts, e2e/src/config/tests-config/accounts/genesis-based-account-manager.ts
=> Fix: e2e tests l2 traffic generation issue

.github/workflows/reuse-linea-besu-package-run-e2e-tests.yml, .github/workflows/reuse-run-e2e-tests.yml, docker/compose-spec-l1-services.yml, docker/compose-spec-l2-services.yml, docker/config/l1-node/el/config.toml, docker/config/l1-node/el/log4j.xml, docker/config/l2-node-besu/log4j.xml, docker/config/linea-besu-sequencer/sequencer.config.toml, docker/linea-mainnet/linea-besu.config.toml, docker/linea-sepolia/linea-besu.config.toml
* Log RPC requests and responses
* Collect Besu L1 node logs
* Remove extra GC options, just go with the default
=> Feat: Improve the logging of Besu during e2e tests

.github/workflows/bridge-ui-publish.yml
=> Fix: bridge ui workflow node version issue

.github/workflows/main.yml
=> fix(ci): filter out commit changes for e2e tests

bridge-ui/src/app/RootLayout.tsx, bridge-ui/src/middleware.ts
This reverts commit 429927ca2cfedee723d08ed53d340f41259dcf1d.
This PR implements issue(s) #964
=> Revert "Adjust CSP header for Cloudflare (#1211)"

jvm-libs/generic/errors/src/main/kotlin/linea/error/JsonRpcErrorResponseException.kt, jvm-libs/generic/json-rpc/src/testFixtures/kotlin/linea/jsonrpc/TestingJsonRpcServer.kt, jvm-libs/linea/clients/eth-logs-searcher/src/test/kotlin/linea/ethapi/LogsSearcherIntTest.kt, jvm-libs/linea/clients/interfaces/src/main/kotlin/linea/ethapi/EthApiClient.kt, jvm-libs/linea/web3j-extensions/build.gradle, jvm-libs/linea/web3j-extensions/src/main/kotlin/linea/web3j/RequestHelper.kt, jvm-libs/linea/web3j-extensions/src/main/kotlin/linea/web3j/ethapi/Web3jEthApiClientFactory.kt, jvm-libs/linea/web3j-extensions/src/main/kotlin/linea/web3j/ethapi/Web3jEthApiClientWithRetries.kt, jvm-libs/linea/web3j-extensions/src/test/kotlin/linea/web3j/ethapi/Web3jEthApiClientWithRetriesTest.kt
=> jvm-libs: eth-api-client stop retry on FINALIZED block not found error

bridge-ui/src/middleware.ts
This PR implements issue(s) #964
=> [Fix] add wss to csp header

besu-plugins/linea-sequencer/sequencer/src/main/java/net/consensys/linea/bl/TransactionProfitabilityCalculator.java, besu-plugins/linea-sequencer/sequencer/src/test/java/net/consensys/linea/sequencer/txselection/selectors/TraceLineLimitTransactionSelectorTest.java, gradle/libs.versions.toml
=> Chore: update Besu to 25.6.0-linea2 and Tuweni to 2.7.1

docker/compose-spec-l2-services.yml
=> feat: update coordinator image tag

contracts/package.json, pnpm-lock.yaml
=> [Chore] Bump hardhat v2.25.0

docs/security.md
=> fix: correct link to audit history in security policy

bridge-ui/src/components/lifi/widget/index.tsx
=> chore(bridge-ui): activate Mayan CCTP bridge

bridge-ui/package.json, pnpm-lock.yaml
=> chore: bump bridge ui layerswap version to 0.1.20

besu-plugins/finalized-tag-updater/src/main/kotlin/net/consensys/linea/FinalizationUpdatePoller.kt
This PR implements issue(s) #1246
=> feat: change stop point from PRAGUE to PARIS

besu-plugins/linea-sequencer/acceptance-tests/src/test/java/linea/plugin/acc/test/extradata/ExtraDataPricingTest.java, besu-plugins/linea-sequencer/sequencer/src/main/java/net/consensys/linea/AbstractLineaSharedPrivateOptionsPlugin.java, besu-plugins/linea-sequencer/sequencer/src/main/java/net/consensys/linea/rpc/methods/LineaEstimateGas.java, besu-plugins/linea-sequencer/sequencer/src/main/java/net/consensys/linea/rpc/services/LineaEstimateGasEndpointPlugin.java, besu-plugins/linea-sequencer/sequencer/src/main/java/net/consensys/linea/sequencer/txpoolvalidation/LineaTransactionPoolValidatorFactory.java, besu-plugins/linea-sequencer/sequencer/src/main/java/net/consensys/linea/sequencer/txpoolvalidation/LineaTransactionPoolValidatorPlugin.java, besu-plugins/linea-sequencer/sequencer/src/main/java/net/consensys/linea/sequencer/txpoolvalidation/validators/SimulationValidator.java, besu-plugins/linea-sequencer/sequencer/src/main/java/net/consensys/linea/sequencer/txselection/selectors/ProfitableTransactionSelector.java, besu-plugins/linea-sequencer/sequencer/src/main/java/net/consensys/linea/sequencer/txselection/selectors/TraceLineLimitTransactionSelector.java, besu-plugins/linea-sequencer/sequencer/src/test/java/net/consensys/linea/sequencer/txpoolvalidation/validators/SimulationValidatorTest.java, gradle/libs.versions.toml
=> Chore: update Besu to 25.7.0-linea4

.github/workflows/all-tools.yml, operations/Dockerfile, operations/package.json, operations/src/commands/eth-transfer.ts, operations/src/utils/eth-transfer/config.ts, operations/src/utils/eth-transfer/misc.ts, operations/src/utils/eth-transfer/transactions.ts, operations/tsconfig.json, pnpm-lock.yaml
=> feat(1280): implement tls for web3signer in eth transfer script

prover/cmd/controller/controller/controller_test.go, prover/zkevm/prover/ecdsa/antichamber.go
=> fix(ecdsa): fail on overflow instead of just crashing

besu-plugins/linea-sequencer/CHANGELOG.md, besu-plugins/linea-sequencer/acceptance-tests/src/test/java/linea/plugin/acc/test/BlobTransactionDenialTest.java, besu-plugins/linea-sequencer/acceptance-tests/src/test/java/linea/plugin/acc/test/EIP7702TransactionDenialTest.java, besu-plugins/linea-sequencer/acceptance-tests/src/test/java/linea/plugin/acc/test/LineaPluginTestBasePrague.java, besu-plugins/linea-sequencer/docs/plugins.md, besu-plugins/linea-sequencer/sequencer/src/main/java/net/consensys/linea/config/LineaTransactionValidatorCliOptions.java, besu-plugins/linea-sequencer/sequencer/src/main/java/net/consensys/linea/config/LineaTransactionValidatorConfiguration.java, besu-plugins/linea-sequencer/sequencer/src/main/java/net/consensys/linea/sequencer/txvalidation/LineaTransactionValidatorPlugin.java, besu-plugins/linea-sequencer/sequencer/src/test/java/net/consensys/linea/sequencer/txvalidation/LineaTransactionValidatorPluginTest.java
This PR implements issue(s) #1266
=> [Feat] Sequencer plugin to block Type4 Tx

docker/compose-spec-l1-services.yml, docker/compose-spec-l2-services.yml, docker/config/linea-besu-sequencer/log4j.xml
=> feat: update linea-besu-package image version in local stack

prover/protocol/compiler/vortex/vortex_test.go
=> minor(vortex): fix the vortex compiler tests

jvm-libs/linea/clients/interfaces/src/main/kotlin/linea/ethapi/EthApiClient.kt, jvm-libs/linea/clients/interfaces/src/testFixtures/kotlin/linea/ethapi/FakeEthApiClient.kt, jvm-libs/linea/web3j-extensions/src/main/kotlin/linea/web3j/ethapi/Web3jEthApiClient.kt, jvm-libs/linea/web3j-extensions/src/main/kotlin/linea/web3j/ethapi/Web3jEthApiClientFactory.kt, jvm-libs/linea/web3j-extensions/src/main/kotlin/linea/web3j/ethapi/Web3jEthApiClientWithRetries.kt
=> eth-api: adds support for blockNumber method

operations/src/utils/eth-transfer/transactions.ts
=> fix: update certs decoding for eth-transfer script

contracts/src/operational/LineaSequencerUptimeFeed.sol
=> fix: update natspec in LineaSequencerUptimeFeed contract

jvm-libs/linea/testing/file-system/src/main/kotlin/net/consensys/linea/testing/filesystem/Files.kt
=> throw FileNotFoundException instead of IllegalArgumentException

build.gradle, docker/compose-spec-l2-services.yml, gradle/libs.versions.toml
=> ci: try fix postgres reset on CI

besu-plugins/linea-sequencer/sequencer/src/main/java/net/consensys/linea/sequencer/liveness/LineaLivenessService.java, besu-plugins/linea-sequencer/sequencer/src/main/java/net/consensys/linea/sequencer/txselection/LineaTransactionSelectorPlugin.java
This PR implements issue(s) #281
=> feat: revised liveness metrics and registered them on start

gradle/libs.versions.toml
=> Chore: update Besu to 25.8.0-linea1

besu-plugins/linea-sequencer/acceptance-tests/build.gradle
=> Fix: Add log4j annotation for GraalVM

.github/workflows/main.yml
=> ci - fix sequencer trigger for linea-sequencer-plugin

besu-plugins/linea-sequencer/acceptance-tests/src/test/java/linea/plugin/acc/test/LineaPluginTestBasePrague.java, gradle/libs.versions.toml
=> Chore: set besu = "25.8.0-linea2"

jvm-libs/generic/json-rpc/src/main/kotlin/net/consensys/linea/jsonrpc/client/LoadBalancingJsonRpcClient.kt, jvm-libs/generic/json-rpc/src/test/kotlin/net/consensys/linea/jsonrpc/client/LoadBalancingJsonRpcClientTest.kt
[This PR fixes the issue in mentioned the slack message](https://consensys.slack.com/archives/C05J55YUDUZ/p1757403729927089?thread_ts=1757349472.306389&cid=C05J55YUDUZ)
=> Fix the sticky failing client in LoadBalancingJsonRpcClient

besu-plugins/linea-sequencer/acceptance-tests/src/test/resources/moduleLimits.toml, besu-plugins/linea-sequencer/acceptance-tests/src/test/resources/moduleLimits_sendRawTx.toml, besu-plugins/linea-sequencer/acceptance-tests/src/test/resources/noModuleLimits.toml, besu-plugins/linea-sequencer/acceptance-tests/src/test/resources/strictModuleLimits.toml, besu-plugins/linea-sequencer/acceptance-tests/src/test/resources/txOverflowModuleLimits.toml, besu-plugins/linea-sequencer/sequencer/src/test/resources/sequencer/line-limits.toml
=> Cleanup: remove SHF_REFERENCE_TABLE from Sequencer tests configuration

.github/workflows/linea-sequencer-plugin-testing.yml
=> Ci improv sequencer plugin deamon enabled

besu-plugins/linea-sequencer/acceptance-tests/src/test/java/linea/plugin/acc/test/rpc/linea/BundleSelectionTimeoutTest.java, besu-plugins/linea-sequencer/sequencer/src/main/java/net/consensys/linea/sequencer/txselection/LineaTransactionSelectorFactory.java, gradle/libs.versions.toml
=> Backports/linea sequencer v3.1 rc6.3 time limited bundle selection

bridge-ui/src/components/bridge/claiming/estimated-time/index.tsx, bridge-ui/src/components/bridge/modal/estimated-time/index.tsx, bridge-ui/src/components/bridge/transaction-history/list-transaction/item/index.tsx, bridge-ui/src/types/bridge.ts, bridge-ui/src/utils/cctp.ts, bridge-ui/src/utils/history/fetchCctpBridgeEvents.ts, bridge-ui/src/utils/index.ts, bridge-ui/src/utils/message.ts
Ticket: https://github.com/Consensys/linea-monorepo/issues/1413
=> feat(bridge-ui): update estimated time when using cctp mode
