Consensys/linea-monorepo

prover/Makefile
They are not needed anymore for compiling the prover
=> Prover: remove corset flags from commands

contracts/Makefile, contracts/package.json
This PR removes the concurrent compilation of contracts as it looks like there is some intermittent file locking or partial file creation and usage in the CI.
```
MalformedAbiError: Not a json
at extractAbi (/home/runner/work/linea-monorepo/linea-monorepo/node_modules/.pnpm/typechain@8.3.2_typescript@5.5.4/node_modules/typechain/src/parser/abiParser.ts:362:11)
at /home/runner/work/linea-monorepo/linea-monorepo/node_modules/.pnpm/typechain@8.3.2_typescript@5.5.4/node_modules/typechain/src/typechain/io.ts:45:31
at Array.filter (<anonymous>)
```
=> Chore: Remove concurrent contract compilation

prover/maths/common/smartvectors/arithmetic_test.go
This PR fixes a failing prover CI caused by a type mismatch in the TestOpBasicEdgeCases test.
```
PASS
ok      github.com/consensys/linea-monorepo/prover/maths/common/smartvectors    0.273s
```
=> Prover: fix type mismatch in TestOpBasicEdgeCases

prover/zkevm/arithmetization/assignment.go
This PR prints out the missing code 77 error messages before os.Exit() to improve error visibility.
before this PR:
```
INFO[0157] module utilization module=add height=349814 limit=1048576 ratio=0.33360862731933594 
ERRO[0157] module utilization module=bin height=611820 limit=524288 ratio=1.1669540405273438 
INFO[0157] module utilization module=binreftable height=196875 limit=262144 ratio=0.7510185241699219 
INFO[0157] module utilization module=blake2fmodexpdata height=11 limit=32768 ratio=0.000335693359375 
...
ERRO[0157] module utilization module=stp height=70123 limit=65536 ratio=1.0699920654296875 
INFO[0157] module utilization module=trm height=14747 limit=65536 ratio=0.2250213623046875 
INFO[0157] module utilization module=txndata height=12207 limit=65536 ratio=0.1862640380859375 …
```
=> chore: improve go-corset error code 77 visibility

prover/zkevm/prover/ecpair/ecpair_constraints.go
This PR fixes LA audit report Issue I.
In the ECPair module we have a column indicating if the current limb is the first line of the current or previous accumulator. As this is natively a boolean condition then we need to enforce it as a constraint to ensure the soundness in case of malicious prover.
Depends on #172. That one needs to be merged first and then the base branch of this one update to main.
=> fix: add binary constraints for accumulators first lines

prover/protocol/compiler/innerproduct/compiler.go, prover/protocol/compiler/innerproduct/context.go, prover/protocol/compiler/innerproduct/innerproduct_test.go
This PR fixes the problem with the round in the inner-product compiler.
The round was increased even if the columns were not required to be collapsed. By the mentioned point, the prover task now depends on the round. The implementation also makes sure that the prover runs in the correct round.
Test cases for different sizes and rounds are added as well.
=> fixing the round problem in the inner-product compiler

contracts/contracts/tokenBridge/TokenBridge.sol, contracts/test/tokenBridge/TokenBridge.ts
=> [Fix] Set default admin for token bridge on reinitialization

prover/circuits/internal/utils.go, prover/circuits/pi-interconnection/assign.go, prover/circuits/pi-interconnection/circuit.go, prover/circuits/pi-interconnection/e2e_test.go, prover/public-input/aggregation.go
* Fix a bug where no comparison between initial and final values of execution public input was being performed.
* Implement the "`rollingHash = 0` implies no update" logic.
* Reduce the runtime of PI circuit tests by running 16 instances instead of 84 and mocking keccak wizard verification.
=> fix compare initial and final values

build.gradle
=> java/kotlin build: allow warning locally with explicit optin

prover/circuits/pi-interconnection/keccak/snark.go, prover/circuits/pi-interconnection/keccak/snark_test.go
This PR fixes a bug in the interconnection circuit caused by the Keccak wrapper's naive assumption that input lanes are padded "cleanly", i.e. equal to zero past their actual lengths.
=> fix don't assume zero-padded lanes

docker/config/prover/v3/prover-config.toml, prover/backend/blobdecompression/prove.go, prover/cmd/prover/cmd/setup.go, prover/config/config.go, prover/config/constants.go
This PR fixes the following issue in the PR:
```
Error: could not prove the blob decompression: error reading the dictionary: open /opt/linea/prover/prover-assets/3.0.0/integration-development/blob-decompression-v1/compressor_dict.bin: no such file or directory
Usage:
prover prove [flags]
Flags:
-h, --help         help for prove
--in string    input file
--large        run the large execution circuit
--out string   output file
Global Flags:
--config string   config file
```
This issue arised after an update on the decompression prover that updates how the dev prover computes its public input (which was different from how the full prover did). As a side-effect, this made the dev prover need to open the dictionary file
(which was not the case before the issue happened) and this was not …
=> Prover: adds field dict_path in config

contracts/docs/operational.md
Fixed typos for clarity in the documentation. Hope this helps.
"Dependant" -> "Dependent"
Dependant is most commonly used as a noun in British English to refer to a person who depends on another for support, especially financially. Dependent, on the other hand, serves as both an adjective and a noun, with its adjectival form widely accepted across American and British English to describe something requiring someone or something else for support or subsistence.
source: https://www.grammarly.com/commonly-confused-words/dependant-vs-dependent
=> docs: cleanup(fix typo) the document

prover/Makefile, prover/README.md, prover/go.mod, prover/go.sum, prover/zkevm/arithmetization/definition.go
This reverts commit 31389b1304c2d5740c3646385f7541586677522d (the bump of beta-v0.8.0-rc6)
=> Revert: Prover: bump to arithmetization beta-v0.8.0-rc6 (#362)

contracts/docs/linea-token-bridge.md, contracts/docs/operational.md, contracts/hardhat.config.ts, contracts/scripts/operational/setRemoteTokenBridgeTask.ts, contracts/scripts/operational/transferProxyAdminOwnership.ts
Note: This was done because of two reasons:
1. The new TokenBridge deploy sets the admin as the safe which is required for the token bridge remote bridge setting and cannot be used in conjunction with the proxy admin owner setting
2. Reusing existing script
=> [Fix] - Remove proxy admin from remote tokenbridge script

docs/audits.md
Include most recent LA audit on prover and gnark. Already published in gnark repo.
=> docs: add reference to LA zkevm audit P2

prover/zkevm/prover/modexp/module_assignement.go
=> err(modexp): returns a 77 error when modexp overflows

prover/Dockerfile
Corset takes up 2 min of docker build on the CI and we don't use it in the prover directly anymore.
=> Prover: build docker wo rust corset

jvm-libs/generic/extensions/kotlin/src/main/kotlin/build/linea/jvm/ResourcesUtil.kt, jvm-libs/generic/extensions/kotlin/src/test/kotlin/build/linea/jvm/ResourcesUtilTest.kt, jvm-libs/linea/blob-compressor/src/main/kotlin/net/consensys/linea/blob/GoNativeBlobCompressor.kt, jvm-libs/linea/blob-decompressor/src/main/kotlin/net/consensys/linea/blob/GoNativeBlobDecompressor.kt
=> jvm: fix resource loading on compressor/decompressor

prover/crypto/ringsis/ringsis_64_16/transerval_hash_bench_test.go
This PR adds a benchmark for the ring-SIS hash with parameters log2-bound=16 and modulus-degree=64
=> bench(sis): adds a benchmark for the ringsis hash

bridge-ui/package.json, bridge-ui/src/components/ConnectButton.tsx, bridge-ui/src/config/wagmi.ts, bridge-ui/src/contexts/web3.context.tsx, pnpm-lock.yaml
=> feat(bridge-ui): Simplify the wallet connection modal

prover/protocol/distributed/common.go, prover/protocol/distributed/compiler/inclusion/inclusion_test.go, prover/protocol/distributed/compiler/permutation/permutation.go, prover/protocol/distributed/compiler/permutation/permutation_test.go, prover/protocol/distributed/compiler/permutation/settings.go, prover/protocol/distributed/distributed.go, prover/protocol/distributed/namebaseddiscoverer/period_separating_module_discoverer.go, prover/protocol/wizard/prover.go, prover/protocol/wizard/verifier.go
=> feat(prover): polish the limitless framework

coordinator/core/src/main/kotlin/net/consensys/zkevm/ethereum/coordination/conflation/ProofGeneratingConflationHandlerImpl.kt
This PR implements issue(s) #549
=> Coordinator fix logging

.github/workflows/coordinator-testing.yml, .github/workflows/reuse-run-e2e-tests.yml
This PR implements issue(s) #542
=> [Fix] Remove _GITHUB_TOKEN_RELEASE_ACCESS from pull_request workflows

.github/workflows/all-tools.yml, .github/workflows/bridge-ui-publish.yml, .github/workflows/cache-docker-images.yml, .github/workflows/coordinator-testing.yml, .github/workflows/postman-build-and-publish.yml, .github/workflows/prover-build-and-publish.yml, .github/workflows/prover-testing.yml, .github/workflows/reuse-run-e2e-tests.yml, .github/workflows/run-smc-tests.yml, .github/workflows/staterecovery-testing.yml, .github/workflows/traces-api-facade-testing.yml, .github/workflows/transaction-exclusion-api-testing.yml
This PR implements issue(s) #545
=> [Feat] GitHub runner upgrades to beefier runners

.github/workflows/cache-docker-images.yml, .github/workflows/coordinator-testing.yml, .github/workflows/prover-testing.yml, .github/workflows/reuse-run-e2e-tests.yml, .github/workflows/run-smc-tests.yml, .github/workflows/staterecovery-testing.yml
This PR implements issue(s) #583 
- Updated `actions/cache` references to 4.2.0
- Use in-built caching for `setup-go`
- 'checkout' before 'setup-go' (https://github.com/actions/setup-go/issues/427#issuecomment-2273249463)
=> [Fix] CI warnings

prover/protocol/column/store.go, prover/protocol/wizard/compiled.go, prover/zkevm/arithmetization/definition.go, prover/zkevm/prover/statemanager/codehashconsistency/consistency.go, prover/zkevm/prover/statemanager/codehashconsistency/consistency_test.go
=> Prover/Codehash Non Power of Two Column Size

coordinator/app/src/test/kotlin/net/consensys/zkevm/coordinator/blockcreation/BlockCreationMonitorTest.kt
This PR implements issue(s) #612
=> coordinator: fix BlockCreationMonitorTest flacky test

docker/compose-spec-l1-services.yml, docker/config/l1-node/cl/config.yaml, docker/config/l1-node/el/config.toml, docker/config/l1-node/generate-genesis.sh
This PR implements issue(s) #706
=> [Feat] Opt-in feature flag to run local stack in Prague/Electra

prover/cmd/dev-tools/corset-checker/main.go, prover/cmd/dev-tools/corset-checker/params.go, prover/cmd/dev-tools/corset-checker/zkevm.go, prover/go.mod, prover/go.sum, prover/zkevm/arithmetization/arithmetization.go, prover/zkevm/arithmetization/definition_test.go, prover/zkevm/arithmetization/files.go, prover/zkevm/checker.go, prover/zkevm/full.go, prover/zkevm/partial.go
This PR does three things:
1. (**checker**) Updates the checker to include the "full suite" when running in benchmark mode.  This is relevant for testing to try and gauge total work done by the prover.
1. (**optimisation**) Adds the ability to specify the optimisation level that `go-corset` applies when compiling the `zkevm.bin` file down to the `air.Schema` which is then consumed by the prover.  In particular, the `bin/checker` is updated to allow the optimisation level to be specified on the command-line for testing purposes.  A `DEFAULT_OPTIMISATION_LEVEL` is provided for normal use.
2. (**metadata**) Exposes the metadata map which is stored within the `zkevm.bin` file.  This is a general purpose mechanism for embedding information within the `zkevm.bin` file.  For example, it …
=> feat: support go corset optimisation and metadata

bridge-ui/src/abis/MessageTransmitterV2.json, bridge-ui/src/types/cctp.ts, bridge-ui/src/types/events.ts, bridge-ui/src/types/index.ts, bridge-ui/src/utils/cctp.ts, bridge-ui/src/utils/events/eventCCTPMessageReceived.ts, bridge-ui/src/utils/events/index.ts, bridge-ui/src/utils/history.ts, bridge-ui/src/utils/index.ts
This PR implements issue(s) #728 
- Feature toggle for transaction history, `isCCTPEnabled == false` -> No USDC transactions in the tx history list
- Implemented CCTPV2 transactions for transaction history. Implemented required utility functions including
- `getCCTPTransactionStatus`
- `getCCTPClaimTx`
- `isCCTPNonceUsed`
- Claim transaction UI flow
- Handle corner case of expired CCTPV2 attestation message
=> [Feat] Bridge UI v2 - Transaction List with CCTPV2 transactions

config/coordinator/coordinator-docker-testnet.config.overrides.toml, config/coordinator/coordinator-docker-traces-v2-override.config.toml, config/coordinator/coordinator-docker.config.toml, config/coordinator/coordinator-local-dev.config-traces-v2.overrides.toml, config/coordinator/coordinator-local-dev.config.overrides.toml, coordinator/app/src/main/kotlin/net/consensys/zkevm/coordinator/app/CoordinatorApp.kt, coordinator/app/src/main/kotlin/net/consensys/zkevm/coordinator/app/L1DependentApp.kt, coordinator/app/src/main/kotlin/net/consensys/zkevm/coordinator/app/config/CoordinatorConfig.kt, coordinator/app/src/main/kotlin/net/consensys/zkevm/coordinator/blockcreation/BlockCreationMonitor.kt, coordinator/app/src/test/kotlin/net/consensys/zkevm/coordinator/app/config/CoordinatorConfigTest.kt, coordinator/app/src/test/resources/configs/coordinator-traces-v2-override.config.toml, coordinator/app/src/test/resources/configs/coordinator.config.toml
* Removes `zk-traces.eth-api`
* `l2.rpc-endpoint` is used in places where `zk-traces.eth-api` was used before (e.g. anchoring and block creation monitor)
=> L2 configs improvement

prover/circuits/blobdecompression/v1/circuit.go
This PR fixes a bug in a recent decompressor refactoring that removed the dictionary assignment of the decompression circuit.
=> fix: dictionary assignment

prover/Dockerfile, prover/config/config-mainnet-full.toml, prover/config/config-sepolia-full.toml
The prover on both testnet and mainnet must be able to accept blobs with both old and new dictionaries until the final blob compressed with the old dictionary has already been aggregated.
=> config: support new dictionary

docker/config/prover/v3/prover-config.toml, prover/lib/compressor/blob/dictionary/dictionary.go
* Add new compression dict path to `docker/config/prover/v3/prover-config.toml`
* Include more info in "dictionary not found" error
=> fix: Change prover config in Docker to include new compressor dict

.github/workflows/linea-besu-package-release.yml, .github/workflows/reuse-linea-besu-package-build-test-push.yml
This PR fixes the issue of `linea-besu-package-release` workflow not being able to be manually cancelled
=> fix: allow cancel for manual triggered linea-besu-package action

prover/go.mod, prover/go.sum
See https://github.com/Consensys/gnark/pull/1487, https://github.com/Consensys/gnark/issues/1483, https://github.com/Consensys/gnark-crypto/pull/680.
Updates only the solver hint for gnark, so no circuit update needed.
~Do not merge to main! We should follow gnark and gnark-crypto master. This is only a backported fix.~
=> fix: use backported gnark-crypto neg-scalar glv fix

besu-plugins/linea-sequencer/acceptance-tests/build.gradle, besu-plugins/linea-sequencer/gradle/dependency-management.gradle, besu-plugins/linea-sequencer/sequencer/build.gradle, besu-plugins/linea-sequencer/sequencer/src/test/java/net/consensys/linea/rpc/methods/LineaSendBundleTest.java, build.gradle, gradle/libs.versions.toml, jvm-libs/linea/besu-libs/build.gradle
Besu for Linea version 25.6.0-linea1 includes the change https://github.com/hyperledger/besu/pull/8589, that renames Maven coordinates for most artifacts, [see here for a translation map](https://github.com/hyperledger/besu/blob/main/CHANGELOG.md#appendix-a), this PR updates Besu and all projects that depends on Besu artifacts to the new coordinates.
=> Chore: Update Besu to 25.6.0-linea1 and artifacts Maven coordinates

besu-plugins/linea-sequencer/gradle/dependency-management.gradle, besu-plugins/linea-sequencer/sequencer/build.gradle, coordinator/persistence/aggregation/build.gradle, coordinator/persistence/blob/build.gradle, gradle/libs.versions.toml, jvm-libs/generic/extensions/tuweni/build.gradle, jvm-libs/linea/besu-libs/build.gradle, jvm-libs/linea/blob-decompressor/build.gradle, jvm-libs/linea/clients/linea-state-manager/build.gradle, jvm-libs/linea/core/traces/build.gradle
Requires #203 Update to Kotlin 2.X
Tuweni new development is now done in the Consensys fork https://github.com/Consensys/tuweni
=> chore: switch to Consensys fork of Tuweni and update it to 2.7.0

docker/config/postman/env, postman/README.md
This PR implements issue(s) #1175
- Enhanced Docker config comments for `L1_LISTENER_INITIAL_FROM_BLOCK` and `L2_LISTENER_INITIAL_FROM_BLOCK` with detailed options and behavior explanation
- Added "(optional)" markers to README documentation for starting block parameters to clarify their optional nature
- Improved consistency between Docker configuration comments and README documentation
- `docker/config/postman/env` - Enhanced configuration comments
- `postman/README.md` - Clarified optional parameter status
=> docs: enhance INITIAL_FROM_BLOCK configuration documentation

besu-plugins/linea-sequencer/sequencer/src/main/java/net/consensys/linea/bundles/BundleForwarder.java, besu-plugins/linea-sequencer/sequencer/src/main/java/net/consensys/linea/bundles/LineaLimitedBundlePool.java, besu-plugins/linea-sequencer/sequencer/src/main/java/net/consensys/linea/bundles/TransactionBundle.java, besu-plugins/linea-sequencer/sequencer/src/main/java/net/consensys/linea/rpc/methods/LineaSendBundle.java, besu-plugins/linea-sequencer/sequencer/src/test/java/net/consensys/linea/bundles/AbstractBundleTest.java, besu-plugins/linea-sequencer/sequencer/src/test/java/net/consensys/linea/bundles/BundleForwarderTest.java, besu-plugins/linea-sequencer/sequencer/src/test/java/net/consensys/linea/bundles/LineaLimitedBundlePoolTest.java, besu-plugins/linea-sequencer/sequencer/src/test/java/net/consensys/linea/bundles/TransactionBundleTest.java, besu-plugins/linea-sequencer/sequencer/src/test/java/net/consensys/linea/rpc/methods/LineaSendBundleTest.java, besu-plugins/linea-sequencer/sequencer/src/test/java/net/consensys/linea/sequencer/txselection/LineaTransactionSelectorFactoryTest.java, besu-plugins/linea-sequencer/sequencer/src/test/java/net/consensys/linea/sequencer/txselection/selectors/BundleConstraintTransactionSelectorTest.java, besu-plugins/linea-sequencer/sequencer/src/test/java/net/consensys/linea/sequencer/txselection/selectors/MaxBundleBlockGasTransactionSelectorTest.java
With this PR is it possible to create a bundle with priority, that means that all the pending transactions it contains have priority, thus they will not need to respect all the gas pricing constraints that normal pending transactions have.
At the moment it is only possible to create bundles with priority internally, bundles that arrives via RPC are always without priority.
=> Feat: Introduce bundle with priority

.github/workflows/prover-testing.yml, prover/Dockerfile, prover/backend/execution/prove.go, prover/go.mod, prover/protocol/dedicated/byte32cmp/decompose.go, prover/protocol/dedicated/byte32cmp/multi_limb_cmp.go, prover/protocol/dedicated/merkle/computemod.go, prover/protocol/dedicated/merkle/merkle_test.go, prover/protocol/dedicated/mimc/linear_hash.go, prover/zkevm/arithmetization/definition.go, prover/zkevm/prover/hash/packing/block.go, prover/zkevm/prover/hash/packing/dedicated/accumulate_upto.go, prover/zkevm/prover/hash/packing/lane.go, prover/zkevm/prover/statemanager/accumulator/define.go, prover/zkevm/prover/statemanager/mimccodehash/define.go
This PR bumps up go version to v1.24.0.
Ran a couple of proof requests and outer proof is successfully generated.
=> update prover to go v1.24.0

coordinator/core/src/main/kotlin/net/consensys/zkevm/ethereum/coordination/conflation/GlobalBlobAwareConflationCalculator.kt, settings.gradle
Logs `trigger=BATCHES_LIMIT` when blob is created due to baches limit
```
new blob: blob=[1..2]2 trigger=BATCHES_LIMIT blobSizeBytes=10560 blobBatchesCount=1 blobBatchesLimit=1 blobBatchesList=[[1..2]2]1
```
Before
```
new blob: blob=[1..2]2 trigger=TRACES_LIMIT blobSizeBytes=10560 blobBatchesCount=1 blobBatchesLimit=1 blobBatchesList=[[1..2]2]1
```
=> coordinator: log BATCHES_LIMIT when blob reaches batches limit

bridge-ui/tsconfig.json, e2e/tsconfig.json, operations/tsconfig.json, postman/README.md, postman/src/application/postman/persistence/subscribers/MessageStatusSubscriber.ts, postman/tsconfig.build.json, postman/tsconfig.json, sdk/sdk-core/tsconfig.json, sdk/sdk-ethers/tsconfig.json, sdk/sdk-viem/tsconfig.json, ts-libs/linea-native-libs/tsconfig.json, tsconfig.json
As per https://github.com/microsoft/Typescript/wiki/Performance#configuring-tsconfigjson-or-jsconfigjson
We should specify that we aren't including too many files in the TypeScript compilation
```json
{
"compilerOptions": {
// ...
},
"include": ["src"],
"exclude": ["**/node_modules", "**/.*/"],
}
```
=> Refactor - Standardize tsconfig.json 'excludes' based on TypeScript documentation
